export const BANK_OPTIONS = [
  { id: 1, name: 'Easypaise', isMicrofinance: true },
  { id: 2, name: 'Jazzcash', isMicrofinance: true },
  { id: 3, name: 'Al Baraka Bank (Pakistan) Limited', isMicrofinance: false },
  { id: 4, name: 'Allied Bank Limited (ABL)', isMicrofinance: false },
  { id: 5, name: 'Askari Bank', isMicrofinance: false },
  { id: 6, name: 'Bank Alfalah Limited (BAFL)', isMicrofinance: false },
  { id: 7, name: 'Bank Al-Habib Limited (BAHL)', isMicrofinance: false },
  { id: 8, name: 'BankIslami Pakistan Limited', isMicrofinance: false },
  { id: 9, name: 'Bank Makramah Limited (BML)', isMicrofinance: false },
  { id: 10, name: 'Bank of Punjab (BOP)', isMicrofinance: false },
  { id: 11, name: 'Bank of Khyber', isMicrofinance: false },
  { id: 12, name: 'Deutsche Bank A.G', isMicrofinance: false },
  {
    id: 13,
    name: 'Dubai Islamic Bank Pakistan Limited (DIB Pakistan)',
    isMicrofinance: false,
  },
  { id: 14, name: 'Faysal Bank Limited (FBL)', isMicrofinance: false },
  { id: 15, name: 'First Women Bank Limited', isMicrofinance: false },
  { id: 16, name: 'Habib Bank Limited (HBL)', isMicrofinance: false },
  { id: 17, name: 'Habib Metropolitan Bank Limited', isMicrofinance: false },
  {
    id: 18,
    name: 'Industrial and Commercial Bank of China',
    isMicrofinance: false,
  },
  {
    id: 19,
    name: 'Industrial Development Bank of Pakistan',
    isMicrofinance: false,
  },
  { id: 20, name: 'JS Bank Limited', isMicrofinance: false },
  { id: 21, name: 'MCB Bank Limited', isMicrofinance: false },
  { id: 22, name: 'MCB Islamic Bank Limited', isMicrofinance: false },
  { id: 23, name: 'Meezan Bank Limited', isMicrofinance: false },
  { id: 24, name: 'National Bank of Pakistan (NBP)', isMicrofinance: false },
  { id: 25, name: 'SadaPay', isMicrofinance: true },
  { id: 26, name: 'Soneri Bank Limited', isMicrofinance: false },
  {
    id: 27,
    name: 'Standard Chartered Bank (Pakistan) Limited (SC Pakistan)',
    isMicrofinance: false,
  },
  { id: 28, name: 'Sindh Bank', isMicrofinance: false },
  {
    id: 29,
    name: 'The Bank of Tokyo-Mitsubishi UFJ (MUFG Bank Pakistan)',
    isMicrofinance: false,
  },
  { id: 30, name: 'United Bank Limited (UBL)', isMicrofinance: false },
  { id: 31, name: 'Zarai Taraqiati Bank Limited', isMicrofinance: false },
]
