export const Constants = {
  baseURL: process.env.NEXT_PUBLIC_BASE_URL,
  statuses: {
    success: 200,
    unauthorized: 401,
    notfound: 404,
  },
  endPoints: {
    login: '/api/auth/login',
    signup: '/api/auth/register',
    verifyOTP: '/api/auth/verify',
    sendVerifyEmail: '/api/auth/send-verify-email',
    getCategories: '/api/category',
    refreshToken: '/api/auth/token/refresh',
    addProductOffers: '/api/products/offers',
    deleteProductOffers: '/api/products/offers/',
    getSingleProduct: '/api/products/',
    getProduct: '/api/products/',
    order: '/api/orders',
    getProductsByCategories: '/api/products/category/{categoryId}',
    getProductsBySubCategories:
      '/api/products/category/{categoryId}/subcategory/{subcategoryId}',
    addProduct: '/api/products/add',
    editProduct: '/api/products',
    uploadImage: '/api/image/upload',
    bulkUpdateVariants: '/api/products/variants/bulk-update',
    getSingleOrder: '/api/orders/',
    orderAll: '/api/orders/all',
    acceptOrder: '/api/orders/',
    cancelOrder: '/api/orders/',
    setProfile: '/api/profile/personal',
    getProfile: '/api/profile',
    setBank: '/api/profile/bank',
    fileUpload: '/api/image/upload',
    getPayouts: '/api/profile/payouts',
    getPaymentLedger: '/api/profile/payment-ledger',
    changePassword: '/api/auth/password',
    resetPassword: '/api/auth/password/reset',
  },
  general: {
    itemPerPage: 10,
    ordersPerPage: 10,
  },
}
